locales:
  en:
    name: Lingala Keyboards
    description: Mobile OS keyboards for the Lingala language from the Divvun group at UiT.
  nb:
    name: Lingala tastatur
    description: Mobiltastatur for Lingala fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
